export const ADD_STUDENT_USER = "ADD_STUDENT_USER"
export const ADD_STUDENT_USER_SUCCESS = "ADD_STUDENT_USER_SUCCESS"
export const ADD_STUDENT_USER_FAIL = "ADD_STUDENT_USER_FAIL"

export const LIST_STUDENT_USER = "LIST_STUDENT_USER"
export const LIST_STUDENT_USER_SUCCESS = "LIST_STUDENT_USER_SUCCESS"
export const LIST_STUDENT_USER_FAIL = "LIST_STUDENT_USER_FAIL"

export const DELETE_STUDENT_USER = "DELETE_STUDENT_USER"
export const DELETE_STUDENT_USER_SUCCESS = "DELETE_STUDENT_USER_SUCCESS"
export const DELETE_STUDENT_USER_FAIL = "DELETE_STUDENT_USER_FAIL"