export const ADD_STAFF_USER = "ADD_STAFF_USER"
export const ADD_STAFF_USER_SUCCESS = "ADD_STAFF_USER_SUCCESS"
export const ADD_STAFF_USER_FAIL = "ADD_STAFF_USER_FAIL"

export const LIST_STAFF_USER = "LIST_STAFF_USER"
export const LIST_STAFF_USER_SUCCESS = "LIST_STAFF_USER_SUCCESS"
export const LIST_STAFF_USER_FAIL = "LIST_STAFF_USER_FAIL"

export const DELETE_STAFF_USER = "DELETE_STAFF_USER"
export const DELETE_STAFF_USER_SUCCESS = "DELETE_STAFF_USER_SUCCESS"
export const DELETE_STAFF_USER_FAIL = "DELETE_STAFF_USER_FAIL"